//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public int RatingValue { get; set; }
        public string Comment { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
